### ISSUE TITLE
Add possibility for delaying ticks of timer

### ISSUE THREAD

**Issue by Kamil93** [mrchimp/tock#18]
Hi
Need something like:
timer.delay(x);

so after it timer will delay next tick for x miliseconds, but just once

I use tock for physic simulation in game, this library is game changer for my project, but to sync physic through network well enough, must be sure that ticks on client and server are almost in same time.

You could do this:
timer.pause();
setTimeout(function() { timer.pause(); }, x);

but I know, that it isn't the best way;

Any help?

**Comment by mrchimp** [comment]
I'm gonna close this. If you still want some changes, holla!
