### ISSUE TITLE
Use unminified file in bower.json "main".

### ISSUE THREAD

**Issue by mrchimp** [mrchimp/tock#28]
The "main" field in bower.json should use the full, uncompressed JS file otherwise it's more hassle than help.

**Comment by oleole90** [comment]
In min.js `msToTimecode` doesn't even accept the 2nd parameter `show_ms`.
I was getting the same output regardless true/false values. So I printed the `msToTimecode` function and found only 1 params declared.

Please update the .min.js or point to the uncompressed version of Tock.
Btw, love it!

**Comment by mrchimp** [comment]
Fixed in 1.0.11. Bower now uses `tock.js`.

Cheers!
