### ISSUE TITLE
Stop Timer after Reaching Certain Time

### ISSUE THREAD

**Issue by Brotakuu** [mrchimp/tock#30]
Thanks for building this.

I'm trying to figure out how to stop the timer once it reaches a certain time. 

For example: Timer starts at 00:00:00, and should stop at 00:05:00

The problem is, how can I continuously check the current value of the timer?

**Comment by mrchimp** [comment]
Tock doesn't currently support this. However, you could do it by using a countdown timer and subtracting the clock time from the total time when displaying it to the user.

**Comment by Brotakuu** [comment]
Was able to get this working. See code:

http://jsfiddle.net/gabrieldeliu/jLg2wvvL/1/
