### ISSUE TITLE
msToTime with Hours

### ISSUE THREAD

**Issue by Brotakuu** [mrchimp/tock#31]
Having some trouble getting msToTime to display with hours (ie: `"02:00:00"`)

    var timer = new Tock({
            callback: function() {
                resultElement.text(timer.msToTime(timer.lap("{hh}:{mm}:{ss}.{ll}")));
                if (start_time && timer.lap() - start_time > run_for) {
                    resultElement.text(resultElement.text() + ' Stopped at ' + timer.msToTime(timer.lap()));
                     timer.stop();
                }
            }
      });

Still outputs just minutes and seconds.

**Comment by Brotakuu** [comment]
Actually, looks like `msToTimecode` is the correct function to call for hours:minutes:seconds.

**Comment by mrchimp** [comment]
Yeah, that's what you want. I should probably improve the docs and put them next to each other...
