### ISSUE TITLE
Need NPM package updated to latest version in repo

### ISSUE THREAD

**Issue by baconface** [mrchimp/tock#33]
Latest version appears to be version 1.0.9 according to Bower. But the NPM's latest version is 1.0.7. I would like the update available so I can use it in the Node.js context fixed in commit c45c69ab052202b83707807d450a73cf5fe7f5d4. Thanks.

**Comment by mrchimp** [comment]
Good point. Will try to sort that out today.

**Comment by baconface** [comment]
:+1:

**Comment by mrchimp** [comment]
Should be good now. Any issues, give me a shout.
