### ISSUE TITLE
when hours is greater than 60, the output string is not expected result

### ISSUE THREAD

**Issue by anrananran** [mrchimp/tock#36]
var timer = new Tock({
                    countdown: true,
                    interval: devider,
                    callback: function() {
                        var str = timer.msToTimecode(timer.lap(), false);
                        console.log(str); //output will begin with 20:00:00 and my expectation is 80:00:00
                    },
                    complete: function() {}
                });
                timer.start(80 * 60 * 60 * 1000);

**Comment by anrananran** [comment]
is there anyone?

**Comment by jonpchin** [comment]
Any update on this?

**Comment by jonpchin** [comment]
@anrananran 
Easy fix is to change line 247 to remove the "% 60", so it would like this:
MS_PER_HOURs = Math.floor((ms / (MS_PER_HOUR))).toString();

**Comment by anrananran** [comment]
@jonpchin Yes, I did,Thank you!

**Comment by mrchimp** [comment]
Hi folks. Sorry this took so long. Should be fixed in v1.0.12
