### ISSUE TITLE
Is it DEMO DOWN?

### ISSUE THREAD

**Issue by facundofarias** [mrchimp/tock#37]
![image](https://cloud.githubusercontent.com/assets/2700564/20601405/c4af44a4-b258-11e6-975c-6235c75b27b2.png)

Or, it's just me?

**Comment by mrchimp** [comment]
Yeah, I've had some server trouble so my whole site is down at the moment. Sorry! Not sure when I'm going to get time to fix it.

**Comment by facundofarias** [comment]
No worries, thanks!

**Comment by mrchimp** [comment]
Demo should be up at http://tock.deviouschimp.co.uk

Might take a while for DNS to propagate.

**Comment by mrchimp** [comment]
Ok, so I messed up the DNS. It *should* work soon.
